---
# tasks file for ansible-role-ubuntu-nginx
- block:
  - name: add key for nginx
    apt_key: url=http://nginx.org/keys/nginx_signing.key

  - name: add repository for nginx
    apt_repository: repo={{ item }}
    with_items:
      - deb http://nginx.org/packages/ubuntu/ {{ ubuntu_nginx_ubuntu_codename }} nginx
      - deb-src http://nginx.org/packages/ubuntu/ {{ ubuntu_nginx_ubuntu_codename }} nginx

  - name: install nginx with apt-get
    apt: name=nginx={{ ubuntu_nginx_version }} update_cache=yes

  become: True
